@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@session = 28aa4c1f-27be-4531-8778-9963eec9b48c

###

GET https://{{host}}/missingauth

###

GET https://{{host}}/badauth
authorization: Basic bad pw

###

GET https://{{host}}/404test
authorization: Basic rpa p@ssword#1

###

GET https://{{host}}/api-docs/
authorization: Basic rpa p@ssword#1

###

GET https://{{host}}/api-spec/
authorization: Basic rpa p@ssword#1

###

GET https://{{host}}/version
authorization: Basic rpa p@ssword#1

###

POST https://{{host}}/processes http/1.1
authorization: Basic rpa p@ssword#1
content-type: application/json

{"process": "Login"}

###

POST https://{{host}}/processes http/1.1
authorization: Basic rpa p@ssword#1
content-type: application/json

{"process": "Test process"}

###

GET https://{{host}}/processes/{{session}}
authorization: Basic rpa p@ssword#1


###

POST https://{{host}}/processes/{{session}}/stop
authorization: Basic rpa p@ssword#1

###

POST https://{{host}}/processes/badid/stop
authorization: Basic rpa p@ssword#1

###

POST https://{{host}}/logoff
authorization: Basic rpa p@ssword#1

