@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@session = 6ee248d1-72f3-4890-af5c-ca9ea6ce4214

###

GET https://{{host}}/missingauth

###

GET https://{{host}}/badauth
authorization: Basic bad pw

###

GET https://{{host}}/404test
authorization: Basic changeme ch@ngeM3

###

GET https://{{host}}/api-docs/
authorization: Basic changeme ch@ngeM3

###

GET https://{{host}}/api-spec/
authorization: Basic changeme ch@ngeM3

###

GET https://{{host}}/version
authorization: Basic changeme ch@ngeM3

###

POST https://{{host}}/processes http/1.1
authorization: Basic changeme ch@ngeM3
content-type: application/json

{"process": "Login"}

###

POST https://{{host}}/processes http/1.1
authorization: Basic changeme ch@ngeM3
content-type: application/json

{"process": "Logout"}

###

POST https://{{host}}/processes http/1.1
authorization: Basic changeme ch@ngeM3
content-type: application/json

{"process": "Test process"}

###

GET https://{{host}}/processes/{{session}}
authorization: Basic changeme ch@ngeM3

###

GET https://{{host}}/processes/{{session}}/badroute
authorization: Basic changeme ch@ngeM3

###

POST https://{{host}}/processes/{{session}}/stop
authorization: Basic changeme ch@ngeM3

###

POST https://{{host}}/processes/badid/stop
authorization: Basic changeme ch@ngeM3
